### ISSUE TITLE
Utilização do orElseThrow

### ISSUE THREAD

**Issue by arthurs159** [GustavoAntunesRocha/recipes-api#1]
Ei Gustavo, olhando seu projeto, senti falta do orElseThrow quando você faz o findById(), muitas vezes só queremos checar no optional se veio algo e se veio, pegar aquela coisa, acho que nesses cenários, você poderia utilizar o OrElseThrow() nos métodos do seu service que faz isso e assim jogando o CustomException, limparia bastante os seus services.

Qualquer coisa, estou à disposição para ajudar xD

**Comment by GustavoAntunesRocha** [comment]
Realmente Arthur, ótima dica!
Fiz as modificações, ficou bem melhor!
Muito obrigado!
